---
- hosts: hartweb.cloud.hartcode.com
  remote_user: hartalex
  vars:
   local_deploy_version: "{{ lookup('env','DEPLOY_VERSION') }}"
   port: "{{ lookup('env','PORT') }}"
  tasks:
    - name: get latest container
      become: true
      command: "gcloud docker pull gcr.io/hartonline-cloud/hartcode.com:{{local_deploy_version}}"
    - name: restart hartcode.com
      become: true
      docker_container:
        name: "{{port}}.hartcode.com"
        image: "gcr.io/hartonline-cloud/hartcode.com:{{local_deploy_version}}"
        state: started
        restart: yes
        recreate: yes
        restart_policy: always
        ports:
          "{{port}}:8811"
