---
- hosts: hartweb.cloud.hartcode.com
  remote_user: hartalex
  vars:
   myport: "{{ lookup('env','PORT') }}"
   commit: "{{ lookup('env', 'TRAVIS_COMMIT') }}"
   tag: "{{ lookup('env', 'TRAVIS_BRANCH') }}"
  tasks:
    - name: get latest container
      become: true
      command: "gcloud docker -- pull gcr.io/hartonline-cloud/hartcode.com:{{tag}}-{{commit}}"
    - name: restart hartcode.com
      become: true
      docker_container:
        name: "{{myport}}.hartcode.com"
        image: "gcr.io/hartonline-cloud/hartcode.com:{{tag}}-{{commit}}"
        state: started
        restart: yes
        recreate: yes
        restart_policy: always
        ports:
          "{{myport}}:8811"
    - wait_for: timeout=5
    - name: Get JSON from page
      uri: url="http://127.0.0.1:{{myport}}/info" return_content=yes
      register: json_response
    - name: Validate commit
      fail: msg="The commits don't match"
      when:  "(json_response.content|from_json)['commit'] is defined and (json_response.content|from_json)['commit'] != commit"
