variables:
  outputimage: "gcr.io/hartonline-cloud/hartcode.com"

stages:
  - build
  - deploy

create_container:
  stage: build
  image: gcr.io/hartonline-cloud/docker:1.0
  script:
    - docker build -t $outputimage:$CI_BUILD_REF .
    - docker tag -f $outputimage:$CI_BUILD_REF $outputimage:latest
    
push_container:
  stage: deploy
  image: gcr.io/hartonline-cloud/docker:1.0
  script:
    - /root/google-cloud-sdk/bin/gcloud docker push $outputimage:$CI_BUILD_REF
    - /root/google-cloud-sdk/bin/gcloud docker push $outputimage:latest
  only:
    - master

deploy_container:
  stage: deploy
  image: gcr.io/hartonline-cloud/ansible:latest
  script:
    - echo $ANSIBLE_DEPLOY_PRIVATE_KEY > /root/.ssh/ansible
    - ansible -m ping all -u hartalex
