variables:
  outputimage: "gcr.io/hartonline-cloud/hartcode.com"

stages:
  - build
  - tag
  - deploy_container
  - deploy_site
  - sync

create_container_ref:
  stage: build
  image: docker:1.11
  script:
    - docker build -t $outputimage:$CI_BUILD_REF .

create_container_tag:
  stage: tag
  image: docker:1.11
  script:
    - docker tag -f $outputimage:$CI_BUILD_REF $outputimage:$CI_BUILD_TAG
    - docker tag -f $outputimage:$CI_BUILD_REF $outputimage:latest
  only:
   - tags

push_container_ref:
  stage: deploy_container
  image: gcr.io/hartonline-cloud/docker:1.3
  script:
    - /root/google-cloud-sdk/bin/gcloud docker push $outputimage:$CI_BUILD_REF
  only:
    - master
    - tags

push_container_tag:
  stage: deploy_container
  image: gcr.io/hartonline-cloud/docker:1.3
  script:
    - /root/google-cloud-sdk/bin/gcloud docker push $outputimage:$CI_BUILD_TAG
    - /root/google-cloud-sdk/bin/gcloud docker push $outputimage:latest
  only:
    - tags

deploy_container:
  stage: deploy_site
  image: gcr.io/hartonline-cloud/ansible:1.2
  script:
    - DEPLOY_VERSION=$CI_BUILD_REF
    - if [[ $CI_BUILD_TAG ]]; then DEPLOY_VERSION=$CI_BUILD_TAG; fi;
    - export DEPLOY_VERSION
    - ansible-playbook .ansible-deploy.yml
  only:
    - tags
sync_github:
  stage: sync
  image: docker:1.12.1-git
  script:
   - git fetch --prune
   - git push --prune git@github.com:hartcode/hartcode.com.git +refs/remotes/origin/*:refs/heads/* +refs/tags/*:refs/tags/* 
