variables:
  outputimage: "gcr.io/hartonline-cloud/hartcode.com"

stages:
  - build
  - deploy_container
  - deploy_site

create_container:
  stage: build
  image: gcr.io/hartonline-cloud/docker:latest
  script:
    - docker build -t $outputimage:$CI_BUILD_REF .
    - docker tag -f $outputimage:$CI_BUILD_REF $outputimage:latest
    
push_container:
  stage: deploy_container
  image: gcr.io/hartonline-cloud/docker:latest
  script:
    - /root/google-cloud-sdk/bin/gcloud docker push $outputimage:$CI_BUILD_REF
    - /root/google-cloud-sdk/bin/gcloud docker push $outputimage:latest
  only:
    - master

deploy_container:
  stage: deploy_site
  image: gcr.io/hartonline-cloud/ansible:latest
  script:
    - echo "-----BEGIN OPENSSH PRIVATE KEY-----" > /root/.ssh/ansible 
    - echo $ANSIBLE_DEPLOY_PRIVATE_KEY >> /root/.ssh/ansible
    - echo "-----END OPENSSH PRIVATE KEY-----" >> /root/.ssh/ansible 
    - chmod 400 /root/.ssh/ansible
    - ansible-playbook .deploy-hartcode.com.yml
  only:
    - master
