build:
  image: gcr.io/hartonline-cloud/docker:1.0
  script:
    - docker build -t $IMAGENAME:$IMAGEVERSION .
    - docker tag -f $IMAGENAME:$IMAGEVERSION $IMAGENAME:latest
    
deploy:
  image: gcr.io/hartonline-cloud/docker:1.0
  script:
    - /root/google-cloud-sdk/bin/gcloud docker push $IMAGENAME:$IMAGEVERSION
    - /root/google-cloud-sdk/bin/gcloud docker push $IMAGENAME:latest