variables:
  inputimage: "gcr.io/hartonline-cloud/docker"
  inputimageversion: "1.0"
  outputimage: "gcr.io/hartonline-cloud/hartcode.com"
build:
  image: $inputimage:$inputimageversion
  script:
    - docker build -t $outputimage:$CI_BUILD_REF .
    - docker tag -f $outputimage:$CI_BUILD_REF $outputimage:latest
    
deploy:
  image: $inputimage:$inputimageversion
  script:
    - /root/google-cloud-sdk/bin/gcloud docker push $outputimage:$CI_BUILD_REF
    - /root/google-cloud-sdk/bin/gcloud docker push $outputimage:latest