sudo: required
cache:
  directories:
    - "$HOME/google-cloud-sdk/"
    - node_modules
language:
  - node_js
  - python
python: 2.7
stages:
  - name: lint
    if: type IN (push, pull_request)
  - name: buildContainer
    if: type IN (push, pull_request)
  - name: releaseContainer
    if: branch IN (test, prod, master) and type = push
services:
  - docker
node_js:
- node
jobs:
  include:
    - stage: lint
      script:
        - npm run lint
    - stage: buildContainer
      script:
        - ./scripts/buildContainer.sh
    - stage: releaseContainer
      script:
        - ./scripts/releaseContainer.sh
notifications:
  slack: hartcode:GqPCaLxnPqXfPJBMjJbEvG81
addons:
  code_climate:
    repo_token: 11ca02b88df3885339c43642e739969e72ad77ab864650018fd6c1c9bdcb5cb0
