sudo: required
cache:
  directories:
    - "$HOME/google-cloud-sdk/"
    - node_modules
language: 
  - node_js
  - python
python: 2.7
services:
  - docker
node_js:
- node
before_install:
  - pip install ansible
script:
- npm run lint
- npm run build
notifications:
  slack: hartcode:GqPCaLxnPqXfPJBMjJbEvG81
addons:
  code_climate:
    repo_token: 11ca02b88df3885339c43642e739969e72ad77ab864650018fd6c1c9bdcb5cb0
after_success:
- npm install -g codeclimate-test-reporter
- codeclimate-test-reporter < lcov.info
- openssl aes-256-cbc -K $encrypted_3b5afcaadad7_key -iv $encrypted_3b5afcaadad7_iv
   -in client-secret.json.enc -out client-secret.json -d 
- ./deployToGCS.sh hartcode.com
- openssl aes-256-cbc -K $encrypted_3b5afcaadad7_key -iv $encrypted_3b5afcaadad7_iv -in ansible.enc -out ansible -d
- openssl aes-256-cbc -K $encrypted_3b5afcaadad7_key -iv $encrypted_3b5afcaadad7_iv -in ansible.enc -out ansible.pub -d
- ansible-playbook -i inventory.yml .ansible-deploy.yml
