sudo: required
cache:
  directories:
    - "$HOME/google-cloud-sdk/"
    - node_modules
language: 
  - node_js
  - python
python: 2.7
stages:
  - name: update_depends
    if: type IN (cron)
  - name: build
    if: type IN (push, pull_request)
  - name: deploy
    if: branch IN (test, prod) and type = push
services:
  - docker
node_js:
- node
jobs:
  include:
    - stage: build
      script:
        - npm run lint
          # - npm install -g codeclimate-test-reporter
          # - codeclimate-test-reporter < lcov.info
        - npm run build
    - stage: deploy
      script:
        - npm run build
        - pip install ansible --user
        - openssl aes-256-cbc -K $encrypted_3b5afcaadad7_key -iv $encrypted_3b5afcaadad7_iv -in secrets.tar.enc -out secrets.tar -d
        - tar xvf secrets.tar
        - ./deployToGCS.sh hartcode.com
        - ./deployAnsible.sh
    - stage: update_depends
      script:
        - ./updateDepends.sh
        - npm run lint
        - npm run build
      after_success:
        - openssl aes-256-cbc -K $encrypted_3b5afcaadad7_key -iv $encrypted_3b5afcaadad7_iv -in secrets.tar.enc -out secrets.tar -d
        - git config --global user.email "travis@travis-ci.org"
        - git config --global user.name "Travis CI"
        - git add package.json
        - git commit -m "Cron Auto Updated Dependencies"
        - tar xvf secrets.tar
        - chmod 400 travis
        - eval "$(ssh-agent -s)"
        - ssh-add travis
        - git remote add deploy git@github.com:hartcode/hartcode.com.git
        - git push deploy HEAD:master
notifications:
  slack: hartcode:GqPCaLxnPqXfPJBMjJbEvG81
addons:
  code_climate:
    repo_token: 11ca02b88df3885339c43642e739969e72ad77ab864650018fd6c1c9bdcb5cb0
