language: node_js
node_js:
  - "node"
script:
    - yarn run lint
    - yarn run build
notifications:
    slack: hartcode:GqPCaLxnPqXfPJBMjJbEvG81
addons:
  code_climate:
    repo_token: 11ca02b88df3885339c43642e739969e72ad77ab864650018fd6c1c9bdcb5cb0
after_success:
  - npm install -g codeclimate-test-reporter
  - codeclimate-test-reporter < lcov.info
