sudo: required
cache:
  directories:
    - "$HOME/google-cloud-sdk/"
    - node_modules
language: node_js
services:
  - docker
node_js:
- node
script:
- npm run lint
- npm run build
notifications:
  slack: hartcode:GqPCaLxnPqXfPJBMjJbEvG81
addons:
  code_climate:
    repo_token: 11ca02b88df3885339c43642e739969e72ad77ab864650018fd6c1c9bdcb5cb0
after_success:
- npm install -g codeclimate-test-reporter
- codeclimate-test-reporter < lcov.info
- openssl aes-256-cbc -K $encrypted_3b5afcaadad7_key -iv $encrypted_3b5afcaadad7_iv
   -in client-secret.json.enc -out client-secret.json -d 
- ./deployToGCS.sh hartcode.com
